name: ci
on:
  push:
    paths:
      - 'lib/**'
      - 'test/**'
      - 'yarn.lock'
      - 'package.json'
      - 'package-lock.json'
    branches:
      - '!*'
      - 'develop'
      - 'stage'
      - 'master'

env:
  GH_PAT: ${{ secrets.GH_PAT }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 20

    services:

      mongodb:
        image: mongo:5
        ports:
          - 27017:27017

      elasticsearch:
        image: blacktop/elasticsearch:7.15.1
        ports:
          - 9200:9200
        options: -e="discovery.type=single-node"

    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          workflow_id: build-docker.yml
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 30
          persist-credentials: false

      - name: Yarn install
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm install

      - name: Test
        run: |
          npm run test
