# https://github.com/probot/semantic-pull-requests
# (chore|feat|docs|fix|refactor|style|test|sonar|hack|release)(:)( )(.{0,80})
# Always validate the PR title AND all the commits
titleAndCommits: true
# Allow use of Merge commits (eg on github: "Merge branch 'master' into feature/ride-unicorns")
# this is only relevant when using commitsOnly: true (or titleAndCommits: true)
allowMergeCommits: true
