name: CI ES 8.0
on:
  push:
    paths:
      - 'lib/**'
      - 'test/**'
      - 'package.json'
      - 'package-lock.json'
      - 'yarn.lock'
    branches:
      - '*'
      - 'develop'
      - 'stage'
      - 'master'

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 20

    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017

    steps:
      - uses: styfle/cancel-workflow-action@0.10.0
        with:
          workflow_id: ci-8-0.yml
          access_token: ${{ github.token }}

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 8.0.0
          security-enabled: false

      - uses: actions/checkout@v3
        with:
          fetch-depth: 30
          persist-credentials: false

      - name: NPM install
        uses: bahmutov/npm-install@v1

      - name: Test
        run: |
          yarn test-ci
