name: CI ES 8.5
on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - 'lib/**'
      - 'test/**'
      - 'package.json'
      - 'package-lock.json'
      - 'yarn.lock'
      - 'release.config.js'
    branches:
      - '*'

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          workflow_id: ci-8-5.yml
          access_token: ${{ github.token }}
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 8.5.3
          security-enabled: false

      - uses: actions/checkout@v3
        with:
          fetch-depth: 30

      - name: NPM install
        uses: bahmutov/npm-install@v1

      - name: Test
        run: |
          yarn test-ci
