name: ci
on:
  push:
    paths:
      - 'lib/**'
      - 'test/**'
      - 'package.json'
      - 'package-lock.json'
    branches:
      - '!*'
      - 'develop'
      - 'stage'
      - 'master'

env:
  GH_PAT: ${{ secrets.GH_PAT }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TS_NODE_TRANSPILE_ONLY: 0

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 20
    strategy:
      matrix:
        node-version: [ 14.x, 17.x ]

    services:

      mongodb:
        image: mongo:5
        ports:
          - 27017:27017

      elasticsearch:
        image: blacktop/elasticsearch:7.15.1
        ports:
          - 9200:9200
        env:
          node.name: es
          discovery.type: single-node
          bootstrap.memory_lock: true
          ES_JAVA_OPTS: -Xms512m -Xmx1024m

    steps:
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          workflow_id: build-docker.yml
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 30
          persist-credentials: false

      - name: NPM install
        uses: bahmutov/npm-install@v1

      - name: Test
        run: |
          npm run test-ci
