name: CI
on:
  push:
    paths:
      - 'lib/**'
      - 'test/**'
      - 'package.json'
      - 'package-lock.json'
      - 'yarn.lock'
    branches:
      - '*'
      - 'develop'
      - 'stage'
      - 'master'

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 20
    strategy:
      matrix:
        es-version: [7.17.0, 8.0.0, 8.2.2]

    services:
      mongodb:
        image: mongo:5
        ports:
          - 27017:27017

    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          workflow_id: build-docker.yml
          access_token: ${{ github.token }}

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: ${{ matrix.es-version }}


      - uses: actions/checkout@v3
        with:
          fetch-depth: 30
          persist-credentials: false

      - name: NPM install
        uses: bahmutov/npm-install@v1

      - name: Test
        run: |
          yarn test-ci
