name: ci
on:
  push:
    paths:
      - 'lib/**'
      - 'test/**'
      - 'package.json'
      - 'package-lock.json'
    branches:
      - '!*'
      - 'develop'
      - 'stage'
      - 'master'

env:
  GH_PAT: ${{ secrets.GH_PAT }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 20
    strategy:
      matrix:
        node-version: [ 14.x, 17.x ]

    services:

      mongodb:
        image: mongo:5
        ports:
          - 27017:27017

    steps:
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 7.15.1

      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          workflow_id: build-docker.yml
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 30
          persist-credentials: false

      - name: NPM install
        uses: bahmutov/npm-install@v1

      - name: get the stats
        run: curl -X Get "http://localhost:9200/_cluster/stats?pretty=true"

      - name: check the elasticsearch whether is running or not
        run: curl -X GET "http://localhost:9200/_cat/nodes?v&pretty"

      - name: Test
        run: |
          npm run test-ci
